### ISSUE TITLE
Proposal Notes

### ISSUE THREAD

**Issue by ragegage** [coleleahy/stack-horizon#1]
I think this proposal is a pretty good start. 
Do you have a style guide for your site? I'd suggest moving "create style guide" into item 1, as that will allow you to style each feature (and the login/signup pages) as you go rather than trying to play catch up with styling afterwards.
Also, please update your API endpoints so that all routing happens on the frontend (including login & signup).

**Comment by coleleahy** [comment]
Thanks, Gage.  Updated my styling timeline, and replaced `/users/new` with `api/users/new` and so on.
